apiVersion: v1
metadata:
  name: NAME
baseDomain: DOMAIN
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      type: m6a.xlarge
      rootVolume:
        size: 100
        type: gp3
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    aws:
      type: m6a.xlarge
      rootVolume:
        size: 100
        type: gp3
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: "" # skip, hive will inject based on it's secrets